### ISSUE TITLE
add link to this repository on rubygems page

### ISSUE THREAD

**Issue by KasTs** [jessedoyle/coffee-script-source#6]
Someone could add the link to this repository in rubygems.

Thanks : )

https://github.com/jessedoyle/coffee-script-source

**Comment by jessedoyle** [comment]
Hi @KasTs! Thanks for your interest!

This repository contains a [_shard_](https://github.com/crystal-lang/shards) for the [Crystal Programming Language](https://crystal-lang.org).

It's a direct port of the original Ruby [`coffee-script-source` gem](https://rubygems.org/gems/coffee-script-source), but it's certainly not related to RubyGems. For that reason I don't think it makes sense to put any links to this repository on RubyGems.

If you're in the Ruby ecosystem, you may be looking for the following repo: https://github.com/rails/ruby-coffee-script.

Thanks!
